### ISSUE TITLE
meta_info.pkl

### ISSUE THREAD

**Issue by Mikedesjardine** [HappyColor/SpeechFormer2#2]
Could you please provide some information about file: meta_info.pkl? What's "shape"?
Thank you!

**Comment by HappyColor** [comment]
`meta_info.pkl` is created by [this function](https://github.com/HappyColor/SpeechFormer2/blob/e8343f939d92eafdad2210ce037fc1ad54e69c26/utils/lmdb_kit.py#L97).
The key `shape` in the `meta_info.pkl` records the shape of the input, i.e., the sequence length and the dimension of the feature. This information will be used in `LMDB_Dataset` ([here](https://github.com/HappyColor/SpeechFormer2/blob/e8343f939d92eafdad2210ce037fc1ad54e69c26/utils/dataset_lmdb.py#L71)) for loading data.

**Comment by lengyuanyuan** [comment]
FileNotFoundError: [Errno 2] No such file or directory: '/148Dataset/data-chen.weidong/lmdb/iemocap_logmel/train/meta_info.pkl' . May I ask how to solve this problem and how to generate this file?
