### ISSUE TITLE
checkpoint is not saved

### ISSUE THREAD

**Issue by Mikedesjardine** [HappyColor/SpeechFormer2#3]
I've successfully run 'train_model.py' with the epoch set to 30, and the results have been printed out as expected. In addition, a new folder labeled 'exp' has been created.
The problem arises with the saving of the trained model and checkpoint. It should be saved in 'exp/SpeechFormer++/datasetname_e30_b32_lr0.0005_hubert12_L2244_expa111/folder_1/checkpoint', however, this directory is empty.

Could you please help me solve this problem? Thank you!

**Comment by HappyColor** [comment]
Please check whether the argument `-save` ([here](https://github.com/HappyColor/SpeechFormer2/blob/e8343f939d92eafdad2210ce037fc1ad54e69c26/train_model.py#L352)) is activated.
