### ISSUE TITLE
Well trained model file and code for inference required

### ISSUE THREAD

**Issue by YuhuiMa** [HappyColor/SpeechFormer2#4]
Could you provide me with the well trained model file for Alzheimer's disease detection (Pitt) tasks and code for inference? Many thanks!

**Comment by HappyColor** [comment]
Sorry, we have not saved the well trained model. As for the inference code, please refer to [here](https://github.com/HappyColor/SpeechFormer2/blob/e8343f939d92eafdad2210ce037fc1ad54e69c26/train_model.py#L186). Thanks.
